In [1]:
import os
os.chdir("C:\\Users\\SAI\\Desktop\\sai\\Handson")
os.getcwd()

'C:\\Users\\SAI\\Desktop\\sai\\Handson'

In [2]:
import pandas as pd
dfCustChurn = pd.read_csv('CustomerChurn.csv')

In [3]:
dfCustChurn.shape

(7043, 21)

In [4]:
dfCustChurn.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ...  DeviceProtection  \
0  No phone service             DSL             No  ...                No   
1                No             DSL            Yes  ...               Yes   
2                No             DSL            Yes  ...                No   
3  No phone service             DSL            Yes  ...               Yes   
4                No     Fiber optic             No  ...                No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [5]:
dfCustChurn = dfCustChurn.drop(['customerID'], axis = 1)

In [6]:
dfCustChurn = dfCustChurn.drop(['TotalCharges'],axis = 1)

In [7]:
dfCustChurn['MultipleLines'] = dfCustChurn['MultipleLines'].replace('No phone service','No')

In [8]:
dfCustChurn['OnlineSecurity'] = dfCustChurn['OnlineSecurity'].replace('No internet service', 'No')

In [9]:
dfCustChurn['OnlineBackup'] = dfCustChurn['OnlineBackup'].replace('No internet service', 'No')

In [10]:
dfCustChurn['DeviceProtection'] = dfCustChurn['DeviceProtection'].replace('No internet service', 'No')

In [11]:
dfCustChurn['TechSupport'] = dfCustChurn['TechSupport'].replace('No internet service', 'No')

In [12]:
dfCustChurn['StreamingTV'] = dfCustChurn['StreamingTV'].replace('No internet service', 'No')

In [13]:
dfCustChurn['StreamingMovies'] = dfCustChurn['StreamingMovies'].replace('No internet service', 'No')

In [14]:
dfCustChurn.columns.values

array(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'Churn'],
      dtype=object)

In [15]:
dfCustChurn.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
Churn                object
dtype: object

In [16]:
dfCustChurn.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
Churn               0
dtype: int64

In [17]:
dfCustChurn.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
Churn               0
dtype: int64

In [18]:
dummydf = pd.get_dummies(dfCustChurn, columns = ["gender", "SeniorCitizen", "Partner", "Dependents", 
       "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity",
       "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV",
       "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod"])

In [19]:
dummydf.columns.values

array(['tenure', 'MonthlyCharges', 'Churn', 'gender_Female',
       'gender_Male', 'SeniorCitizen_0', 'SeniorCitizen_1', 'Partner_No',
       'Partner_Yes', 'Dependents_No', 'Dependents_Yes',
       'PhoneService_No', 'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_Yes', 'InternetService_DSL',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No', 'OnlineSecurity_Yes', 'OnlineBackup_No',
       'OnlineBackup_Yes', 'DeviceProtection_No', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_Yes', 'StreamingTV_No',
       'StreamingTV_Yes', 'StreamingMovies_No', 'StreamingMovies_Yes',
       'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype=object)

In [20]:
dummydf.head()

tenure  MonthlyCharges Churn  gender_Female  gender_Male  SeniorCitizen_0  \
0       1           29.85    No              1            0                1   
1      34           56.95    No              0            1                1   
2       2           53.85   Yes              0            1                1   
3      45           42.30    No              0            1                1   
4       2           70.70   Yes              1            0                1   

   SeniorCitizen_1  Partner_No  Partner_Yes  Dependents_No  \
0                0           0            1              1   
1                0           1            0              1   
2                0           1            0              1   
3                0           1            0              1   
4                0           1            0              1   

              ...              StreamingMovies_Yes  Contract_Month-to-month  \
0             ...                                0                        1   
1             ...                                0                        0   
2             ...                                0                        1   
3             ...                                0                        0   
4             ...                                0                        1   

   Contract_One year  Contract_Two year  PaperlessBilling_No  \
0                  0                  0                    0   
1                  1                  0                    1   
2                  0                  0                    0   
3                  1                  0                    1   
4                  0                  0                    0   

   PaperlessBilling_Yes  PaymentMethod_Bank transfer (automatic)  \
0                     1                                        0   
1                     0                                        0   
2                     1                                        0   
3                     0                                        1   
4                     1                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  
0                           0  
1                           1  
2                           1  
3                           0  
4                           0  

[5 rows x 39 columns]

In [21]:
dummydf.dtypes

tenure                                       int64
MonthlyCharges                             float64
Churn                                       object
gender_Female                                uint8
gender_Male                                  uint8
SeniorCitizen_0                              uint8
SeniorCitizen_1                              uint8
Partner_No                                   uint8
Partner_Yes                                  uint8
Dependents_No                                uint8
Dependents_Yes                               uint8
PhoneService_No                              uint8
PhoneService_Yes                             uint8
MultipleLines_No                             uint8
MultipleLines_Yes                            uint8
InternetService_DSL                          uint8
InternetService_Fiber optic                  uint8
InternetService_No                           uint8
OnlineSecurity_No                            uint8
OnlineSecurity_Yes             

In [22]:
import numpy as np
dummydf['MonthlyCharges'] = dummydf['MonthlyCharges'].replace(r'^\s*$',np.nan,regex = True)

In [24]:
dummydf['MonthlyCharges'].isna().sum()

0

In [24]:
#dummydf['TotalCharges'] = dummydf['TotalCharges'].fillna(0)

In [25]:
#dummydf['TotalCharges'] = dummydf['TotalCharges'].astype(float)

In [25]:
from sklearn.preprocessing import MinMaxScaler

scaler= MinMaxScaler()
dummydf[['tenure','MonthlyCharges']] = scaler.fit_transform(dummydf[['tenure','MonthlyCharges']])

In [26]:
dummydf.head()

tenure  MonthlyCharges Churn  gender_Female  gender_Male  \
0  0.013889        0.115423    No              1            0   
1  0.472222        0.385075    No              0            1   
2  0.027778        0.354229   Yes              0            1   
3  0.625000        0.239303    No              0            1   
4  0.027778        0.521891   Yes              1            0   

   SeniorCitizen_0  SeniorCitizen_1  Partner_No  Partner_Yes  Dependents_No  \
0                1                0           0            1              1   
1                1                0           1            0              1   
2                1                0           1            0              1   
3                1                0           1            0              1   
4                1                0           1            0              1   

              ...              StreamingMovies_Yes  Contract_Month-to-month  \
0             ...                                0                        1   
1             ...                                0                        0   
2             ...                                0                        1   
3             ...                                0                        0   
4             ...                                0                        1   

   Contract_One year  Contract_Two year  PaperlessBilling_No  \
0                  0                  0                    0   
1                  1                  0                    1   
2                  0                  0                    0   
3                  1                  0                    1   
4                  0                  0                    0   

   PaperlessBilling_Yes  PaymentMethod_Bank transfer (automatic)  \
0                     1                                        0   
1                     0                                        0   
2                     1                                        0   
3                     0                                        1   
4                     1                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  
0                           0  
1                           1  
2                           1  
3                           0  
4                           0  

[5 rows x 39 columns]

In [27]:
dummydf['Churn'] = dummydf['Churn'].replace('Yes',1).replace('No',0)

In [28]:
Y = dummydf[['Churn']]

In [29]:
X = dummydf.drop(['Churn'],axis = 1)

In [30]:
X.columns

Index(['tenure', 'MonthlyCharges', 'gender_Female', 'gender_Male',
       'SeniorCitizen_0', 'SeniorCitizen_1', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_Yes', 'StreamingMovies_No',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [31]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,stratify = Y, test_size = 0.25, random_state = 3)

In [32]:
Accuracy = list()
Model = list()
Leaving_Ratio = list()
Staying_Ratio = list()

In [33]:
def accuracy(confusion_matrix):
    diagonal_sum = confusion_matrix.trace()
    sum_of_all_elements = confusion_matrix.sum()
    yield diagonal_sum/sum_of_all_elements
    
    Leaving_Ratio = confusion_matrix[0][0]/sum(confusion_matrix[0])
    yield Leaving_Ratio
    yield confusion_matrix[1][1]/sum(confusion_matrix[1])

In [34]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train,Y_train)
Y_pred = pd.Series(classifier.predict(X_test), index = X_test.index)

c:\python37\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [35]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('Logistic Regression')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)
#print(classification_report(Y_test, Y_pred))

[[1162  132]
 [ 226  241]]
0.7967064168086314
0.8979907264296755
0.5160599571734475


In [36]:
Y_pred.head()

6040    1
3655    0
5932    1
5053    0
5860    1
dtype: int64

In [37]:
PredictedChrun = pd.DataFrame(Y_pred, columns = ['PredictedChurn'])

In [38]:
type(PredictedChrun)

pandas.core.frame.DataFrame

In [39]:
PredictedChrun.shape

(1761, 1)

In [40]:
Y_pred.shape

(1761,)

In [41]:
X_test.shape

(1761, 38)

In [44]:
Xtestdf = pd.DataFrame(X_test,columns = ['tenure', 'MonthlyCharges', 'gender_Female', 'gender_Male',
       'SeniorCitizen_0', 'SeniorCitizen_1', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_Yes', 'TechSupport_No', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_Yes', 'StreamingMovies_No',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'])

In [43]:
Ytestdf =  pd.DataFrame(Y_test, columns = ['Churn'])

In [45]:
data = pd.concat([Xtestdf,Ytestdf],axis =1)

In [46]:
data['PredictedChurn'] = PredictedChrun['PredictedChurn']

In [47]:
data.head()
#data.shape

tenure  MonthlyCharges  gender_Female  gender_Male  SeniorCitizen_0  \
6040  0.013889        0.522388              1            0                1   
3655  0.444444        0.011443              1            0                1   
5932  0.069444        0.758209              0            1                1   
5053  0.222222        0.613930              1            0                1   
5860  0.027778        0.514925              1            0                1   

      SeniorCitizen_1  Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  \
6040                0           1            0              1               0   
3655                0           0            1              1               0   
5932                0           0            1              1               0   
5053                0           0            1              0               1   
5860                0           1            0              1               0   

           ...        Contract_One year  Contract_Two year  \
6040       ...                        0                  0   
3655       ...                        0                  0   
5932       ...                        0                  0   
5053       ...                        0                  0   
5860       ...                        0                  0   

      PaperlessBilling_No  PaperlessBilling_Yes  \
6040                    1                     0   
3655                    1                     0   
5932                    0                     1   
5053                    0                     1   
5860                    1                     0   

      PaymentMethod_Bank transfer (automatic)  \
6040                                        0   
3655                                        1   
5932                                        0   
5053                                        0   
5860                                        1   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
6040                                      0                               0   
3655                                      0                               0   
5932                                      0                               1   
5053                                      1                               0   
5860                                      0                               0   

      PaymentMethod_Mailed check  Churn  PredictedChurn  
6040                           1      1               1  
3655                           0      0               0  
5932                           0      1               1  
5053                           0      0               0  
5860                           0      1               1  

[5 rows x 40 columns]

In [48]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion = 'gini',random_state =1, max_depth = 5)
classifier.fit(X_train,Y_train)
Y_pred = pd.Series(classifier.predict(X_test), index = X_test.index)

In [49]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Gini_5')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)
#print(classification_report(Y_test,Y_pred))
#Accuracy_List.append(acc)

[[1110  184]
 [ 183  284]]
0.7915956842703009
0.8578052550231839
0.6081370449678801


In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

Classifier = DecisionTreeClassifier(criterion = 'gini',random_state =1, max_depth = 4)
classifier.fit(X_train,Y_train)
Y_pred = pd.Series(classifier.predict(X_test), index = X_test.index)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Gini_4')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1110  184]
 [ 183  284]]
0.7915956842703009
0.8578052550231839
0.6081370449678801


In [51]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

Classifier = DecisionTreeClassifier(criterion = 'gini',random_state =1, max_depth = 2)
classifier.fit(X_train,Y_train)
Y_pred = pd.Series(classifier.predict(X_test), index = X_test.index)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Gini_4')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1110  184]
 [ 183  284]]
0.7915956842703009
0.8578052550231839
0.6081370449678801


In [52]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

Classifier = DecisionTreeClassifier(criterion = 'gini',random_state =1, max_depth = 3)
classifier.fit(X_train,Y_train)
Y_pred = pd.Series(classifier.predict(X_test), index = X_test.index)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Gini_3')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1110  184]
 [ 183  284]]
0.7915956842703009
0.8578052550231839
0.6081370449678801


In [53]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

Classifier = DecisionTreeClassifier(criterion = 'gini',random_state =1, max_depth = 6)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Gini_6')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1110  184]
 [ 183  284]]
0.7915956842703009
0.8578052550231839
0.6081370449678801


In [54]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

Classifier = DecisionTreeClassifier(criterion = 'gini',random_state =1, max_depth = 7)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Gini_7')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1110  184]
 [ 183  284]]
0.7915956842703009
0.8578052550231839
0.6081370449678801


In [55]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

classifier = DecisionTreeClassifier(criterion = 'entropy',random_state =1, max_depth = 5)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Entropy_5')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1136  158]
 [ 222  245]]
0.7842135150482681
0.8778979907264297
0.5246252676659529


In [56]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

classifier = DecisionTreeClassifier(criterion = 'entropy',random_state =1, max_depth = 4)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Entropy_4')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1207   87]
 [ 288  179]]
0.787052810902896
0.9327666151468316
0.38329764453961457


In [57]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

classifier = DecisionTreeClassifier(criterion = 'entropy',random_state =1, max_depth = 6)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Entropy_6')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1127  167]
 [ 195  272]]
0.794434980124929
0.8709428129829985
0.582441113490364


In [58]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

classifier = DecisionTreeClassifier(criterion = 'entropy',random_state =1, max_depth = 3)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Entropy_3')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1207   87]
 [ 288  179]]
0.787052810902896
0.9327666151468316
0.38329764453961457


In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

classifier = DecisionTreeClassifier(criterion = 'entropy',random_state =1, max_depth = 2)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Entropy_2')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1061  233]
 [ 188  279]]
0.760931289040318
0.8199381761978362
0.5974304068522484


In [60]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

classifier = DecisionTreeClassifier(criterion = 'entropy',random_state =1, max_depth = 7)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('DecisionTreeClassifier_Entropy_7')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1169  125]
 [ 255  212]]
0.7842135150482681
0.9034003091190108
0.4539614561027837


In [61]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 12,criterion = 'entropy',random_state = 1,max_depth = 5)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)

c:\python37\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [62]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Entropy_5')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1213   81]
 [ 293  174]]
0.7876206700738216
0.9374034003091191
0.37259100642398285


In [63]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'entropy',random_state = 1,max_depth = 4)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Entropy_4')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1242   52]
 [ 319  148]]
0.7893242475865985
0.9598145285935085
0.3169164882226981


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'entropy',random_state = 1,max_depth = 4)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Entropy_4')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1242   52]
 [ 319  148]]
0.7893242475865985
0.9598145285935085
0.3169164882226981


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'entropy',random_state = 1,max_depth = 3)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Entropy_3')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1257   37]
 [ 351  116]]
0.7796706416808632
0.9714064914992272
0.24839400428265523


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [66]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'entropy',random_state = 1,max_depth = 6)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Entropy_6')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1180  114]
 [ 261  206]]
0.787052810902896
0.9119010819165378
0.4411134903640257


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'entropy',random_state = 1,max_depth = 3)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Entropy_3')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1257   37]
 [ 351  116]]
0.7796706416808632
0.9714064914992272
0.24839400428265523


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [68]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 12,criterion = 'gini',random_state = 1,max_depth = 5)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)

c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [69]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc = accuracy(cm)
print(acc)
#print(classification_report(Y_test,Y_pred))
#Accuracy_List.append(acc)

[[1209   85]
 [ 282  185]]
<generator object accuracy at 0x000001CF3D3258B8>


In [70]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'gini',random_state = 1,max_depth = 5)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc = accuracy(cm)
print(acc)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Gini_5')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1209   85]
 [ 282  185]]
<generator object accuracy at 0x000001CF3D325C78>
0.7915956842703009
0.9343122102009274
0.3961456102783726


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [71]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'gini',random_state = 1,max_depth = 4)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc = accuracy(cm)
print(acc)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Gini_4')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1244   50]
 [ 316  151]]
<generator object accuracy at 0x000001CF3D325A98>
0.7921635434412265
0.9613601236476044
0.3233404710920771


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [72]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'gini',random_state = 1,max_depth = 3)
classifier.fit(X_train,Y_train)
Y_pred = pd.Series(classifier.predict(X_test), index = X_test.index)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc = accuracy(cm)
print(acc)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Gini_3')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1262   32]
 [ 365  102]]
<generator object accuracy at 0x000001CF3D3258B8>
0.7745599091425327
0.9752704791344667
0.21841541755888652


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [73]:
Y_pred.head()

6040    0
3655    0
5932    1
5053    0
5860    0
dtype: int64

In [74]:
data = pd.concat([X_test,Y_test],axis = 1)

In [75]:
PredictedChurn = pd.DataFrame(Y_pred, columns=['PredictedChurn'])

In [76]:
PredictedChurn.head()

PredictedChurn
6040               0
3655               0
5932               1
5053               0
5860               0

In [77]:
data['PredictedChurn'] = PredictedChurn['PredictedChurn']

In [78]:
data.shape

(1761, 40)

In [79]:
data.head()

tenure  MonthlyCharges  gender_Female  gender_Male  SeniorCitizen_0  \
6040  0.013889        0.522388              1            0                1   
3655  0.444444        0.011443              1            0                1   
5932  0.069444        0.758209              0            1                1   
5053  0.222222        0.613930              1            0                1   
5860  0.027778        0.514925              1            0                1   

      SeniorCitizen_1  Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  \
6040                0           1            0              1               0   
3655                0           0            1              1               0   
5932                0           0            1              1               0   
5053                0           0            1              0               1   
5860                0           1            0              1               0   

           ...        Contract_One year  Contract_Two year  \
6040       ...                        0                  0   
3655       ...                        0                  0   
5932       ...                        0                  0   
5053       ...                        0                  0   
5860       ...                        0                  0   

      PaperlessBilling_No  PaperlessBilling_Yes  \
6040                    1                     0   
3655                    1                     0   
5932                    0                     1   
5053                    0                     1   
5860                    1                     0   

      PaymentMethod_Bank transfer (automatic)  \
6040                                        0   
3655                                        1   
5932                                        0   
5053                                        0   
5860                                        1   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
6040                                      0                               0   
3655                                      0                               0   
5932                                      0                               1   
5053                                      1                               0   
5860                                      0                               0   

      PaymentMethod_Mailed check  Churn  PredictedChurn  
6040                           1      1               0  
3655                           0      0               0  
5932                           0      1               1  
5053                           0      0               0  
5860                           0      1               0  

[5 rows x 40 columns]

In [80]:
data.to_csv(r'C:\\Users\\SAI\\Desktop\\sai\\Handson\\RFCG3Churn.csv')

In [81]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'gini',random_state = 1,max_depth = 6)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc = accuracy(cm)
print(acc)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Gini_6')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1194  100]
 [ 267  200]]
<generator object accuracy at 0x000001CF3D38A4F8>
0.7915956842703009
0.9227202472952086
0.4282655246252677


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [82]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
classifier = RandomForestClassifier(n_estimators = 12,criterion = 'gini',random_state = 1,max_depth = 7)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,Y_pred)
print(cm)
acc = accuracy(cm)
print(acc)
acc,yes,no = accuracy(cm)
print(acc)
print(yes)
print(no)
Model.append('RandomForestClassifier_Gini_7')
Accuracy.append(acc)
Leaving_Ratio.append(yes)
Staying_Ratio.append(no)

[[1179  115]
 [ 252  215]]
<generator object accuracy at 0x000001CF3D38A318>
0.7915956842703009
0.91112828438949
0.4603854389721627


c:\python37\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [83]:
Acctable = {'Model': Model,'Accuracy': Accuracy,'Leaving_Ratio':Leaving_Ratio,'Staying_Ratio':Staying_Ratio}

In [84]:
Accuracytable = pd.DataFrame(Acctable)

In [87]:
Accuracytable

Model  Accuracy  Leaving_Ratio  Staying_Ratio
0                Logistic Regression  0.796706       0.897991       0.516060
1      DecisionTreeClassifier_Gini_5  0.791596       0.857805       0.608137
2      DecisionTreeClassifier_Gini_4  0.791596       0.857805       0.608137
3      DecisionTreeClassifier_Gini_4  0.791596       0.857805       0.608137
4      DecisionTreeClassifier_Gini_3  0.791596       0.857805       0.608137
5      DecisionTreeClassifier_Gini_6  0.791596       0.857805       0.608137
6      DecisionTreeClassifier_Gini_7  0.791596       0.857805       0.608137
7   DecisionTreeClassifier_Entropy_5  0.784214       0.877898       0.524625
8   DecisionTreeClassifier_Entropy_4  0.787053       0.932767       0.383298
9   DecisionTreeClassifier_Entropy_6  0.794435       0.870943       0.582441
10  DecisionTreeClassifier_Entropy_3  0.787053       0.932767       0.383298
11  DecisionTreeClassifier_Entropy_2  0.760931       0.819938       0.597430
12  DecisionTreeClassifier_Entropy_7  0.784214       0.903400       0.453961
13  RandomForestClassifier_Entropy_5  0.787621       0.937403       0.372591
14  RandomForestClassifier_Entropy_4  0.789324       0.959815       0.316916
15  RandomForestClassifier_Entropy_4  0.789324       0.959815       0.316916
16  RandomForestClassifier_Entropy_3  0.779671       0.971406       0.248394
17  RandomForestClassifier_Entropy_6  0.787053       0.911901       0.441113
18  RandomForestClassifier_Entropy_3  0.779671       0.971406       0.248394
19     RandomForestClassifier_Gini_5  0.791596       0.934312       0.396146
20     RandomForestClassifier_Gini_4  0.792164       0.961360       0.323340
21     RandomForestClassifier_Gini_3  0.774560       0.975270       0.218415
22     RandomForestClassifier_Gini_6  0.791596       0.922720       0.428266
23     RandomForestClassifier_Gini_7  0.791596       0.911128       0.460385